### ISSUE TITLE
CsccContext  IMethodName

### ISSUE THREAD

**Issue by Louis-Jin** [svstoll/cscc-recommender#20]
I see CsccContext class has a property, an instance of IMethodName, to store which method is invoked. 
I think our recommender should also be able to suggest things like "setVisible", "getVisible"(type should be IPropertyName), and "this.lineContextVisitor"(type should be IFieldName). Is the current implementation indexing these from the Contexts dataset?

**Comment by Louis-Jin** [comment]
Because in Extraction dataset, I saw the proposal has those types: IMethodName, IPropertyName, IFieldName, IParameterName(this one I think we don't need). If the Contexts dataset is also like this, maybe the current implementation has some issue?

**Comment by svstoll** [comment]
Actually, this property of the `CsccContext` is only used if a completion event doesn't have a variable or type reference. In this case, we query the index with the type that declares the method body where the completion event occurred. The indexing happens in the `LineContextVisitor`, we don't store the invoked method in the `CsccContext` directly.

But you are right that we currently only consider completion events where a `IMethodName` was selected. However, we could easily extend the `LineContextVisitor` to index properties and fields as well. We would only need to extend the visitor methods for property references and field references like it is done in `ch.uzh.ifi.ase.csccrecommender.mining.LineContextVisitor#visit(cc.kave.commons.model.ssts.references.IMethodReference, ch.uzh.ifi.ase.csccrecommender.mining.LineContext)`. However, I'm not sure how much sense it makes to suggest field names as they are typically only accessible inside the class where they were declared. But we don't consider method visibility anyway. I'm not sure if the original paper mentions if they considered such type of information.

**Comment by Louis-Jin** [comment]
I just checked all the examples in the paper. I think they didn't count field either. So maybe just add IPropertyName?

**Comment by svstoll** [comment]
Yes, I think we should add those. I kind of forgot that setters and getters are not considered methods in C#.
