### ISSUE TITLE
Implement Inverted Index with Apache Lucene

### ISSUE THREAD

**Issue by svstoll** [svstoll/cscc-recommender#6]
The inverted index need to be persistent in some way. We don't want to recalculate it every time, we run the actual recommender.

**Comment by Louis-Jin** [comment]
I added some functions in order to store which id should be used next for documents. And for storing document, I plan to store them in one json file. If found out to be too big, improve then.

**Comment by Louis-Jin** [comment]
I added some functions in order to store which id should be used next for documents. And for storing document, I plan to store them in one json file. If found out to be too big, improve then.

**Comment by svstoll** [comment]
We do not really have to store the documents in a separate file. Since it's not a lot of data, we can store them directly in the Lucene index which should also perform better. I merged the latest version with a working Lucene index into the master branch.
